dist: trusty
os: linux
language: php
php:
- '7.1.14'
services:
- mysql
install:
- mysql -e 'CREATE DATABASE aurora;'
- composer self-update 1.10.17
- composer install
- composer run pre-config
script:
- chmod +x ./travis.sh
- ./travis.sh -t npm
- ./travis.sh -t build
- ./travis.sh -t pack
after_success: 
- ./travis.sh -t upload
env:
  global:
  - PRODUCT_NAME=webmail-pro-mta
  